### ISSUE TITLE
Blows up on branches that are deleted on the remote server

### ISSUE THREAD

**Issue by matthewdeanmartin** [galactics/git-meta#1]
Thanks for writing this tool.

It is routine to delete a feature branch (or to delete branches for any reason). I don't think the app should even care if a remote branch is deleted, except maybe it a sign of unpushed code (but not always, completed branches on our team are always deleted) or a minor nuisance.

But if there are any remotely deleted branches, the tool blows up. It also doesn't say which repo has the problem.

I had to add this even see what it was complaining about.
```
def iter(self, clean=False, filter_status=None):
        for path in self.repolist:
            print(path)
            try:
                repo = Repo(path)
```

```
~\thing\search_ui                                          (prod-in-flight:-1) [ OK ]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "~\.local\bin\git-meta.exe\__main__.py", line 7, in <module>
  File "~\.local\pipx\venvs\git-meta\Lib\site-packages\gitmeta.py", line 508, in main
    meta.scan(filter_status=filter_status, clean=args["--clean"])
  File "~\.local\pipx\venvs\git-meta\Lib\site-packages\gitmeta.py", line 462, in scan
    print(repo.statusline(line_width))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~\.local\pipx\venvs\git-meta\Lib\site-packages\gitmeta.py", line 288, in statusline
    remote_diff = self.remote_diff()
                  ^^^^^^^^^^^^^^^^^^
  File "~\.local\pipx\venvs\git-meta\Lib\site-packages\gitmeta.py", line 207, in remote_diff
    base = self.merge_base(branch, remote)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~\.local\pipx\venvs\git-meta\Lib\site-packages\git\repo\base.py", line 674, in merge_b

ase
    lines = self.git.merge_base(*rev, **kwargs).splitlines()  # List[str]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~\.local\pipx\venvs\git-meta\Lib\site-packages\git\cmd.py", line 741, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~\.local\pipx\venvs\git-meta\Lib\site-packages\git\cmd.py", line 1315, in _call_proces

s
    return self.execute(call, **exec_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~\.local\pipx\venvs\git-meta\Lib\site-packages\git\cmd.py", line 1109, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git merge-base CPRS-2583_work origin/CPRS-2583_work
  stderr: 'fatal: Not a valid object name origin/CPRS-2583_work'
```

**Comment by matthewdeanmartin** [comment]
It looks like the python git wrapper now throws `git.exc.GitCommandError`

Also, on my machine I can't get it to display `errstr`
```
            try:
                repo = Repo(path)
            except (git.exc.GitError, git.exc.GitCommandError):
                errstr = TagStr(
                    "<color=red>The directory\n  %s\nis not a valid repository." % path
                )
```

**Comment by galactics** [comment]
Hello and thank you for your feedback.
I have corrected the issue in my last push, so you should be OK now with deleted branches.

Good catch !
